CREATE TABLE ERS_REIMBURSEMENT_TYPE(
RT_ID       NUMBER(*,0) NOT NULL PRIMARY KEY,
RT_TYPE     VARCHAR2(30) NOT NULL);

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
RS_ID       NUMBER(*,0) NOT NULL PRIMARY KEY,
RS_STATUS   VARCHAR2(30) NOT NULL);

CREATE TABLE ERS_USER_ROLES(
UR_ID       NUMBER(*,0) NOT NULL PRIMARY KEY,
UR_ROLE     VARCHAR2(40));

CREATE TABLE ERS_USERS(
U_ID        NUMBER(*,0) NOT NULL PRIMARY KEY,
U_USERNAME  VARCHAR2(40) NOT NULL UNIQUE,
U_PASSWORD  VARCHAR2(40) NOT NULL,
U_FIRSTNAME VARCHAR2(30),
U_LASTNAME  VARCHAR2(30),
U_EMAIL     VARCHAR2(100) UNIQUE,
UR_ID       NUMBER(*,0) NOT NULL,
CONSTRAINT FK_USER_ROLE FOREIGN KEY (UR_ID) REFERENCES ERS_USER_ROLES(UR_ID));

CREATE TABLE ERS_REIMBURSEMENTS(
R_ID            NUMBER(*,0) NOT NULL PRIMARY KEY,
R_AMOUNT        NUMBER(22,2) NOT NULL,
R_DESCRIPTION   VARCHAR2(100),
R_RECEIPT       BLOB,
R_SUBMITTED     TIMESTAMP NOT NULL,
R_RESOLVED      TIMESTAMP,
U_ID_AUTHOR     NUMBER(*,0) NOT NULL,
U_ID_RESOLVER   NUMBER(*,0),
RT_TYPE         NUMBER(*,0) NOT NULL,
RT_STATUS       NUMBER(*,0) NOT NULL,
CONSTRAINT FK_USER_AUTHOR FOREIGN KEY (U_ID_AUTHOR) REFERENCES ERS_USERS(U_ID),
CONSTRAINT FK_USER_RESOLVER FOREIGN KEY (U_ID_RESOLVER) REFERENCES ERS_USERS(U_ID),
CONSTRAINT FK_REQUEST_TYPE FOREIGN KEY (RT_TYPE) REFERENCES ERS_REIMBURSEMENT_TYPE(RT_ID),
CONSTRAINT FK_REQUEST_STATUS FOREIGN KEY (RT_STATUS) REFERENCES ERS_REIMBURSEMENT_STATUS(RS_ID));

--Create the user roles
INSERT INTO ERS_USER_ROLES(UR_ID, UR_ROLE) VALUES(1, 'Manager');
INSERT INTO ERS_USER_ROLES(UR_ID, UR_ROLE) VALUES(2, 'Employee');

--Create the reimbursement types
INSERT INTO ERS_REIMBURSEMENT_TYPE(RT_ID, RT_TYPE) VALUES (1, 'Travel');
INSERT INTO ERS_REIMBURSEMENT_TYPE(RT_ID, RT_TYPE) VALUES (2, 'Testing Certifications');
INSERT INTO ERS_REIMBURSEMENT_TYPE(RT_ID, RT_TYPE) VALUES (3, 'Morty Insurance');
INSERT INTO ERS_REIMBURSEMENT_TYPE(RT_ID, RT_TYPE) VALUES (4, 'Portal Gun Replacement');

--Create the reimbursement states
INSERT INTO ERS_REIMBURSEMENT_STATUS(RS_ID, RS_STATUS) VALUES (1, 'Pending');
INSERT INTO ERS_REIMBURSEMENT_STATUS(RS_ID, RS_STATUS) VALUES (2, 'Approved');
INSERT INTO ERS_REIMBURSEMENT_STATUS(RS_ID, RS_STATUS) VALUES (3, 'Denied');

--Create the Managers
INSERT INTO ERS_USERS(U_ID, U_USERNAME, U_PASSWORD, U_FIRSTNAME, U_LASTNAME, U_EMAIL, UR_ID) VALUES(1, 'pm', 'eyepatch', 'President', 'Morty', 'EvilMorty@Citadel.com', 1);
INSERT INTO ERS_USERS(U_ID, U_USERNAME, U_PASSWORD, U_FIRSTNAME, U_LASTNAME, U_EMAIL, UR_ID) VALUES(2, 'rs', 'wubbalubbadubdub', 'Rick', 'Sanchez', 'RickestRick@Citadel.com', 1);
INSERT INTO ERS_USERS(U_ID, U_USERNAME, U_PASSWORD, U_FIRSTNAME, U_LASTNAME, U_EMAIL, UR_ID) VALUES(3, 'mm', 'lookatme', 'Mister', 'Meeseeks', 'ExistenceIsPain@Citadel.com', 1);

--Create the employees
INSERT INTO ERS_USERS(U_ID, U_USERNAME, U_PASSWORD, U_FIRSTNAME, U_LASTNAME, U_EMAIL, UR_ID) VALUES(4, 'js', 'pathetic', 'Jerry', 'Smith', 'ImJerrySmith@Citadel.com', 2);
INSERT INTO ERS_USERS(U_ID, U_USERNAME, U_PASSWORD, U_FIRSTNAME, U_LASTNAME, U_EMAIL, UR_ID) VALUES(5, 'bs', 'morecomplete', 'Beth', 'Smith', 'EquineSurgeon@Citadel.com', 2);
INSERT INTO ERS_USERS(U_ID, U_USERNAME, U_PASSWORD, U_FIRSTNAME, U_LASTNAME, U_EMAIL, UR_ID) VALUES(6, 'ss', 'summerissafe', 'Summer', 'Smith', 'KeepSummerSafe@Citadel.com', 2);
INSERT INTO ERS_USERS(U_ID, U_USERNAME, U_PASSWORD, U_FIRSTNAME, U_LASTNAME, U_EMAIL, UR_ID) VALUES(7, 'tinyrick', 'imtinyrick', 'Tiny', 'Rick', 'TinyRick@Citadel.com', 2);


