CREATE TABLE ERS_REIMBURSEMENT_TYPE(
RT_ID       NUMBER(*,0) NOT NULL PRIMARY KEY,
RT_TYPE     VARCHAR2(30) NOT NULL);

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
RS_ID       NUMBER(*,0) NOT NULL PRIMARY KEY,
RS_STATUS   VARCHAR2(30) NOT NULL);

CREATE TABLE ERS_USER_ROLES(
UR_ID       NUMBER(*,0) NOT NULL PRIMARY KEY,
UR_ROLE     VARCHAR2(40));

CREATE TABLE ERS_USERS(
U_ID        NUMBER(*,0) NOT NULL PRIMARY KEY,
U_USERNAME  VARCHAR2(40) NOT NULL UNIQUE,
U_PASSWORD  VARCHAR2(40) NOT NULL,
U_FIRSTNAME VARCHAR2(30),
U_LASTNAME  VARCHAR2(30),
U_EMAIL     VARCHAR2(100) UNIQUE,
UR_ID       NUMBER(*,0) NOT NULL,
CONSTRAINT FK_USER_ROLE FOREIGN KEY (UR_ID) REFERENCES ERS_USER_ROLES(UR_ID));

CREATE TABLE ERS_REIMBURSEMENTS(
R_ID            NUMBER(*,0) NOT NULL PRIMARY KEY,
R_AMOUNT        NUMBER(22,2) NOT NULL,
R_DESCRIPTION   VARCHAR2(100),
R_RECEIPT       BLOB,
R_SUBMITTED     TIMESTAMP NOT NULL,
R_RESOLVED      TIMESTAMP,
U_ID_AUTHOR     NUMBER(*,0) NOT NULL,
U_ID_RESOLVER   NUMBER(*,0),
RT_TYPE         NUMBER(*,0) NOT NULL,
RT_STATUS       NUMBER(*,0) NOT NULL,
CONSTRAINT FK_USER_AUTHOR FOREIGN KEY (U_ID_AUTHOR) REFERENCES ERS_USERS(U_ID),
CONSTRAINT FK_USER_RESOLVER FOREIGN KEY (U_ID_RESOLVER) REFERENCES ERS_USERS(U_ID),
CONSTRAINT FK_REQUEST_TYPE FOREIGN KEY (RT_TYPE) REFERENCES ERS_REIMBURSEMENT_TYPE(RT_ID),
CONSTRAINT FK_REQUEST_STATUS FOREIGN KEY (RT_STATUS) REFERENCES ERS_REIMBURSEMENT_STATUS(RS_ID));

