-- SQL Lab
-- rollback

-- 2.1 select
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE LASTNAME = 'King';
SELECT * FROM EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;
/

-- 2.2 order by
SELECT * FROM ALBUM ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY ASC;
/

-- 2.3 INSERT INTO
INSERT INTO GENRE VALUES(26, 'FILLER26'); 
INSERT INTO GENRE VALUES(27, 'FILLER27');

INSERT INTO EMPLOYEE VALUES(9, 'Hill', 'Hank', 'Sales Support Agent', 2,
    '20-JUL-1987', '02-DEC-2010', 
    '9001 Memes Way', 'Charleston', 'SC', 'United States', '29492', 
    '1-123-456-7890', '1-123-456-7899', 'best@memes.org');
INSERT INTO EMPLOYEE VALUES(10, 'Lee', 'Bob', 'IT Staff', 6,
    '30-NOV-1968', '18-JAN-2002', 
    '1 This St', 'Porters Lake', 'NS', 'Canada', 'B3E 1H4', 
    '1-987-654-3210', '1-987-654-3211', 'best@streetnames.net');

INSERT INTO CUSTOMER VALUES(60, 'Hank', 'Hill', 'Strickland Propane',
    '9001 Memes Way', 'Charleston', 'SC', 'United States', '29492', 
    '1-123-456-7890', '1-123-456-7899', 'best@memes.org', 9);
INSERT INTO CUSTOMER VALUES(61, 'Bob', 'Lee', NULL,
    '1 This St', 'Porters Lake', 'NS', 'Canada', 'B3E 1H4', 
    '1-987-654-3210', '1-987-654-3211', 'best@streetnames.net', 10);
/


-- 2.4 UPDATE
UPDATE CUSTOMER SET FIRSTNAME='Robert', LASTNAME='Walter'
WHERE FIRSTNAME='Aaron' AND LASTNAME='Mitchell';
UPDATE ARTIST SET NAME='CCR' 
WHERE NAME='Creedence Clearwater Revival';
/

-- 2.5 LIKE
SELECT * FROM INVOICE 
WHERE BILLINGADDRESS LIKE 'T%';
/

-- BETWEEN
SELECT * FROM INVOICE
WHERE TOTAL BETWEEN 15 AND 50;
SELECT * FROM EMPLOYEE
WHERE HIREDATE BETWEEN '1-JUN-2003' AND '1-MAR-2004';
/

-- 2.7 DELETE; default constraint on FOREIGN KEY columns is ON DELETE RESTRICT; 
--             drop and set to ON DELETE CASCADE to delete record & dependents to avoid broken references.
ALTER TABLE INVOICE
DROP CONSTRAINT FK_INVOICECUSTOMERID;
ALTER TABLE INVOICE
ADD CONSTRAINT FK_INVOICECUSTOMERID
    FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
    ON DELETE CASCADE;

ALTER TABLE INVOICELINE
DROP CONSTRAINT FK_INVOICELINEINVOICEID;
ALTER TABLE INVOICELINE
ADD CONSTRAINT FK_INVOICELINEINVOICEID
    FOREIGN KEY(INVOICEID) REFERENCES INVOICE(INVOICEID)
    ON DELETE CASCADE;
    
DELETE FROM CUSTOMER
WHERE FIRSTNAME='Robert' AND LASTNAME='Walter';


-- 3.1 System Defined Functions


-- GOAL: 5.0