package com.revature.jdbc;

/**
 * CREATE DATABASE TABLES FOR BANKING APP
 */
public interface CreateBank {

	String TRANSACTION_TABLE_NAME = "TRANSACTION";
	String BANK_ACCOUNT_TABLE_NAME = "BANK_ACCOUNT";
	String USER_BANK_ACCOUNT_TABLE_NAME = "USER_BANK_ACCOUNT";
	String CREDENTIALS_TABLE_NAME = "CREDENTIAL";
	String USER_TABLE_NAME = "BANK_USER";
	String SUPER_USER_TABLE_NAME = "SUPER_USER";

	String CREATE_TRANSACTION_TABLE = "CREATE TABLE " + TRANSACTION_TABLE_NAME + "(" + "USER_ID VARCHAR(36) NOT NULL,"
			+ "ACCOUNT_ID VARCHAR(36) NOT NULL," + "PRIMARY KEY (USER_ID, ACCOUNT_ID) " + ")";

	String CREATE_BANK_ACCOUNT_TABLE = "CREATE TABLE " + BANK_ACCOUNT_TABLE_NAME + "("
			+ "ACCOUNT_ID VARCHAR(36) NOT NULL," + "BALANCE NUMBER(19, 4)," + "PRIMARY KEY (ACCOUNT_ID) " + ")";

	String CREATE_USER_BANK_ACCOUNT_TABLE = "CREATE TABLE " + USER_BANK_ACCOUNT_TABLE_NAME + "("
			+ "USER_ID VARCHAR(36) NOT NULL," + "ACCOUNT_ID VARCHAR(36) NOT NULL,"
			+ "PRIMARY KEY (USER_ID, ACCOUNT_ID) " + ")";

	// TODO: CREDENTIALS HAS TO BE TIED TO AN ACCOUNT--not null?
	String CREATE_CREDENTIALS_TABLE = "CREATE TABLE " + CREDENTIALS_TABLE_NAME + "(" + "USERNAME VARCHAR(20) NOT NULL,"
			+ "PASSWORD VARCHAR(20) NOT NULL," + "ACCOUNT_ID VARCHAR(36) NOT NULL," + "PRIMARY KEY (USERNAME) " + ")";

	String CREATE_USER_TABLE = "CREATE TABLE " + USER_TABLE_NAME + "(" + "USER_ID VARCHAR(36) NOT NULL,"
			+ "FIRSTNAME VARCHAR(36) NOT NULL," + "LASTNAME VARCHAR(36) NOT NULL," + "BIRTHDATE DATE DEFAULT (sysdate),"
			+ "PRIMARY KEY (USER_ID) " + ")";

	String CREATE_SUPER_USER_TABLE = "CREATE TABLE " + SUPER_USER_TABLE_NAME + "(" + "USER_ID VARCHAR(36) NOT NULL,"
			+ "FIRSTNAME VARCHAR(36) NOT NULL," + "LASTNAME VARCHAR(36) NOT NULL," + "BIRTHDATE DATE DEFAULT (sysdate),"
			+ "PRIMARY KEY (USER_ID) " + ")";

}
