--SELECT * FROM ALBUM WHERE ALBUMID=2 OR ALBUMID = 235;
--
--SELECT NAME FROM ARTIST WHERE ARTISTID=2;
--
----SELECT FIRSTNAME, LASTNAME FROM EMPLOYEE WHERE TITLE='IT STAFF' GROUP BY LASTNAME;
--SELECT COUNT(EMPLOYEEID),COUNTRY,CITY FROM EMPLOYEE 
----WHERE TITLE='IT Staff' 
--GROUP BY CITY, COUNTRY HAVING COUNT(EMPLOYEEID) >1
--ORDER BY COUNT(EMPLOYEEID) DESC, CITY ASC;
--
--SELECT CONCAT(CONCAT(NAME, ': '), COMPOSER) AS DERPCOL FROM TRACK
--WHERE TRACKID < 5;
--
--SELECT * FROM INVOICE
--INNER JOIN CUSTOMER
--ON INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID
--WHERE INVOICE.CUSTOMERID = 1
--ORDER BY INVOICE.INVOICEID ASC;


CREATE TABLE STUDENTS(S_ID INT, S_NAME VARCHAR(10), SC_ID INT);
CREATE TABLE SCHOOLS(SC_ID INT, SC_NAME VARCHAR(10));

INSERT INTO STUDENTS VALUES(1, 'MATT', 10);
INSERT INTO STUDENTS VALUES(2, 'JOSH', 20);
INSERT INTO STUDENTS VALUES(3, 'JUSTIN', 30);
INSERT INTO STUDENTS VALUES(4, 'TIM', 40);

INSERT INTO SCHOOLS VALUES(10, 'AL');
INSERT INTO SCHOOLS VALUES(20, 'UGA');
INSERT INTO SCHOOLS VALUES(30, 'OSU');
INSERT INTO SCHOOLS VALUES(40, 'USF');
INSERT INTO SCHOOLS VALUES(50, 'UNR');

SELECT * FROM SCHOOLS
LEFT JOIN STUDENTS
ON SCHOOLS.SC_ID = STUDENTS.SC_ID;