CREATE TABLE USERACCOUNTS (USERID INT, ACCOUNTID INT, USERNAME VARCHAR2(10), PASSWORD VARCHAR2(10), ACCOUNTBAL NUMBER(20,2));
/
--DROP TABLE USERACCOUNTS;

CREATE SEQUENCE USER_SEQUENCE
MINVALUE 100
MAXVALUE 99999999
INCREMENT BY 2;

CREATE SEQUENCE BANK_SEQUENCE
MINVALUE 1000
MAXVALUE 9999999999
INCREMENT BY 5;

INSERT INTO USERACCOUNTS
(USERID, ACCOUNTID, USERNAME, PASSWORD, ACCOUNTBAL) VALUES (USER_SEQUENCE.NEXTVAL,  BANK_SEQUENCE.NEXTVAL,'marko', 'polo', 22.5);

CREATE OR REPLACE PROCEDURE UPDATE_ACC_BAL
(MONEY IN NUMBER, A_ID IN NUMBER) AS
    BEGIN
        UPDATE USERACCOUNTS SET ACCOUNTBAL = MONEY WHERE ACCOUNTID = A_ID;
        COMMIT;
    END;
    /
EXECUTE UPDATE_ACC_BAL (5000.05, 1075);
EXECUTE UPDATE_ACC_BAL (100,1250);

SELECT * FROM USERACCOUNTS WHERE (USERNAME,PASSWORD) IN 
(SELECT USERNAME, PASSWORD FROM USERACCOUNTS WHERE USERNAME='julian' AND PASSWORD='jd');



