<--User Roles Table-->
CREATE TABLE ERS_USER_ROLES 
(
    UR_ID NUMBER (*, 0) GENERATED ALWAYS AS IDENTITY,
    UR_ROLE VARCHAR2 (40 BYTE),
    CONSTRAINT ERS_USER_ROLES_PK PRIMARY KEY(UR_ID)
);

<--Users Table-->
CREATE TABLE ERS_USERS
(
    U_ID NUMBER (*, 0) GENERATED ALWAYS AS IDENTITY,
    U_USERNAME VARCHAR2 (40 BYTE),
    U_PASSWORD VARCHAR2 (40 BYTE),
    U_FIRSTNAME VARCHAR2 (30 BYTE),
    U_LASTNAME VARCHAR2 (30 BYTE),
    U_EMAIL VARCHAR2 (100 BYTE),
    UR_ID NUMBER (*, 0),
    CONSTRAINT ERS_USERS_PK PRIMARY KEY (U_ID),
    CONSTRAINT ERS_USERS_U_USERNAME_UN UNIQUE (U_USERNAME),
    CONSTRAINT ERS_USERS_U_EMAIL_UN UNIQUE (U_EMAIL),
    CONSTRAINT SYS_C07742 FOREIGN KEY (UR_ID)
    REFERENCES ERS_USER_ROLES (UR_ID)
);

<--REIMBURSMENT STATUS TABLE-->
CREATE TABLE ERS_REIMBURSMENT_STATUS
(
    RS_ID NUMBER (*,0) GENERATED ALWAYS AS IDENTITY,
    RS_STATUS VARCHAR2 (30 BYTE),
    CONSTRAINT ERS_REIMBURSMENT_STATUS_PK PRIMARY KEY (RS_ID)
);

<--REIMBURSMENT TYPE TABLE-->
CREATE TABLE ERS_REIMBURSMENT_TYPE 
(
    RT_ID NUMBER (*,0) GENERATED ALWAYS AS IDENTITY,
    RT_TYPE VARCHAR2 (30 BYTE),
    CONSTRAINT ERS_REIMBURSMENT_TYPE_PK PRIMARY KEY (RT_ID)
);

<--REIMBURSMENT MAIN TABLE-->
CREATE TABLE ERS_REIMBURSMENTS
(
    R_ID NUMBER (*,0) GENERATED ALWAYS AS IDENTITY,
    R_AMOUNT NUMBER (22,2),
    R_DESCRIPTION VARCHAR2 (100 BYTE),
    R_RECEIPT BLOB,
    R_SUBMITTED TIMESTAMP,
    R_RESOLVED TIMESTAMP,
    U_ID_AUTHOR NUMBER (*,0),
    U_ID_RESOLVER NUMBER (*,0),
    RT_TYPE NUMBER (*,0),
    RT_STATUS NUMBER (*,0),
    CONSTRAINT ERS_REIMBURSEMENTS_PK PRIMARY KEY (R_ID),
    CONSTRAINT SYS_C007753 FOREIGN KEY (U_ID_AUTHOR)
    REFERENCES ERS_USERS (U_ID),
    CONSTRAINT SYS_C007754 FOREIGN KEY (U_ID_RESOLVER)
    REFERENCES ERS_USERS (U_ID),
    CONSTRAINT SYS_C007755 FOREIGN KEY (RT_TYPE)
    REFERENCES ERS_REIMBURSMENT_TYPE (RT_ID),
    CONSTRAINT SYS_C007756 FOREIGN KEY (RT_STATUS)
    REFERENCES ERS_REIMBURSMENT_STATUS (RS_ID)
);