DROP TABLE ERS_USERS;
DROP TABLE ERS_USER_ROLES;
DROP TABLE ERS_REIMBURSEMENTS;
DROP TABLE ERS_REIMBURSEMENT_TYPE;
DROP TABLE ERS_REIMBURSEMENT_STATUS;

CREATE TABLE ERS_USERS
(
    U_ID NUMBER(*,0) NOT NULL,
    U_USERNAME VARCHAR2(40),
    U_PASSWORD VARCHAR2(40),
    U_FIRSTNAME VARCHAR2(30),
    U_LASTNAME VARCHAR2(30),
    U_EMAIL VARCHAR2(100),
    UR_ID NUMBER(*,0) NOT NULL
);
CREATE TABLE ERS_USER_ROLES
(
    UR_ROLES_ID NUMBER(*,0) NOT NULL,
    UR_ROLE VARCHAR2(40)
);
CREATE TABLE ERS_REIMBURSEMENTS
(
    R_ID NUMBER(*,0) NOT NULL,
    R_AMOUNT NUMBER(22,2),
    R_DESCRIPTION VARCHAR2(100),
    R_RECEIPT BLOB,
    R_SUBMITTED TIMESTAMP,
    R_RESOLVED TIMESTAMP,
    U_ID_AUTHOR NUMBER(*,0) NOT NULL,
    U_ID_RESOLVER NUMBER(*,0) NOT NULL,
    RT_RE_ID NUMBER(*,0) NOT NULL,
    RS_RE_ID NUMBER(*,0) NOT NULL
    
);
CREATE TABLE ERS_REIMBURSEMENT_TYPE
(
    RT_ID NUMBER(*,0) NOT NULL,
    RT_TYPE VARCHAR2(30)
);
CREATE TABLE ERS_REIMBURSEMENT_STATUS
(
    RS_ID NUMBER(*,0) NOT NULL,
    RS_STATUS VARCHAR2(30)
);

CREATE SEQUENCE U_ID INCREMENT BY 1 START WITH 1 MAXVALUE 65535 NOCACHE NOCYCLE;
