--------------------------------------------------------
--  File created - Monday-February-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACCOUNT_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "JOSEPHJUSTN"."ACCOUNT_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 23 START WITH 100001439 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence USER_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "JOSEPHJUSTN"."USER_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "JOSEPHJUSTN"."BANK_ACCOUNT" 
   (	"ACCOUNTTYPE" NUMBER DEFAULT 0, 
	"BALANCE" FLOAT(126) DEFAULT 0.00, 
	"USER1" VARCHAR2(20 BYTE), 
	"USER2" VARCHAR2(20 BYTE), 
	"APPROVED" NUMBER DEFAULT 0, 
	"ACCOUNTNUMBER" NUMBER(9,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "JOSEPHJUSTN"."BANK_ACCOUNT"."ACCOUNTTYPE" IS '0: regular 1:joint';
   COMMENT ON COLUMN "JOSEPHJUSTN"."BANK_ACCOUNT"."APPROVED" IS '0: no 1: yes';
--------------------------------------------------------
--  DDL for Table BANK_USER
--------------------------------------------------------

  CREATE TABLE "JOSEPHJUSTN"."BANK_USER" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"ADDRESSNUMBER" NUMBER, 
	"ADDRESSSTREET" VARCHAR2(20 BYTE), 
	"ZIPCODE" NUMBER, 
	"ACCOUNTTYPE" NUMBER, 
	"USERID" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View MY_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "JOSEPHJUSTN"."MY_VIEW" ("TITLE") AS 
  SELECT TITLE FROM ALBUM
;
REM INSERTING into JOSEPHJUSTN.BANK_ACCOUNT
SET DEFINE OFF;
Insert into JOSEPHJUSTN.BANK_ACCOUNT (ACCOUNTTYPE,BALANCE,USER1,USER2,APPROVED,ACCOUNTNUMBER) values (0,253.99,'customer',null,1,100001255);
Insert into JOSEPHJUSTN.BANK_ACCOUNT (ACCOUNTTYPE,BALANCE,USER1,USER2,APPROVED,ACCOUNTNUMBER) values (0,1234.56,'admin',null,1,0);
REM INSERTING into JOSEPHJUSTN.BANK_USER
SET DEFINE OFF;
Insert into JOSEPHJUSTN.BANK_USER (USERNAME,PASSWORD,FIRSTNAME,LASTNAME,ADDRESSNUMBER,ADDRESSSTREET,ZIPCODE,ACCOUNTTYPE,USERID) values ('admin','passw0rd','Michael','Hawkins',88,'Road Way',59687,2,0);
Insert into JOSEPHJUSTN.BANK_USER (USERNAME,PASSWORD,FIRSTNAME,LASTNAME,ADDRESSNUMBER,ADDRESSSTREET,ZIPCODE,ACCOUNTTYPE,USERID) values ('employee','passw0rd','John','Smith',5432,'Street Rd',33456,1,1);
Insert into JOSEPHJUSTN.BANK_USER (USERNAME,PASSWORD,FIRSTNAME,LASTNAME,ADDRESSNUMBER,ADDRESSSTREET,ZIPCODE,ACCOUNTTYPE,USERID) values ('customer','passw0rd','Bob','Johnson',555,'Street St',99999,0,2);
--------------------------------------------------------
--  DDL for Index BANK_ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JOSEPHJUSTN"."BANK_ACCOUNT_PK" ON "JOSEPHJUSTN"."BANK_ACCOUNT" ("ACCOUNTNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BANK_CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JOSEPHJUSTN"."BANK_CUSTOMER_PK" ON "JOSEPHJUSTN"."BANK_USER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CLEAR_ORPHAN_ACCOUNTS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JOSEPHJUSTN"."CLEAR_ORPHAN_ACCOUNTS" 
AFTER DELETE ON BANK_USER 
BEGIN
  DELETE FROM BANK_ACCOUNT WHERE USER1 IS NULL AND USER2 IS NULL;
END;
/
ALTER TRIGGER "JOSEPHJUSTN"."CLEAR_ORPHAN_ACCOUNTS" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADD_BANK_ACCOUNT_JOINT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "JOSEPHJUSTN"."ADD_BANK_ACCOUNT_JOINT" 
(
  USER1IN IN VARCHAR2,
  USER2IN IN VARCHAR2
) AS 
BEGIN
  INSERT INTO BANK_ACCOUNT VALUES(1, 0, USER1IN, USER2IN, 0, ACCOUNT_ID_SEQUENCE.NEXTVAL);
END ADD_BANK_ACCOUNT_JOINT;

/
--------------------------------------------------------
--  DDL for Procedure ADD_BANK_ACCOUNT_SINGLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "JOSEPHJUSTN"."ADD_BANK_ACCOUNT_SINGLE" 
(
  USER1IN IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO BANK_ACCOUNT VALUES(0, 0, USER1IN, NULL, 0, ACCOUNT_ID_SEQUENCE.NEXTVAL);
END ADD_BANK_ACCOUNT_SINGLE;

/
--------------------------------------------------------
--  DDL for Procedure ADD_BANK_USER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "JOSEPHJUSTN"."ADD_BANK_USER" 
(
  USERNAMEIN IN VARCHAR2 
, PASSWORDIN IN VARCHAR2 
, FIRSTNAMEIN IN VARCHAR2 
, LASTNAMEIN IN VARCHAR2 
, ADDRESSNUMBERIN IN NUMBER 
, ADDRESSSTREETIN IN VARCHAR2 
, ZIPCODEIN IN NUMBER 
) AS 
BEGIN
    INSERT INTO BANK_USER VALUES(USERNAMEIN, PASSWORDIN, FIRSTNAMEIN, LASTNAMEIN, ADDRESSNUMBERIN, ADDRESSSTREETIN, ZIPCODEIN, 0, ACCOUNT_ID_SEQUENCE.NEXTVAL);
END ADD_BANK_USER;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_EMPTY_ACCOUNTS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "JOSEPHJUSTN"."DELETE_EMPTY_ACCOUNTS" 
(
  USERIN IN VARCHAR2 
) AS 
BEGIN
  DELETE FROM BANK_ACCOUNT WHERE BALANCE=0 AND APPROVED=1 AND (USER1=USERIN OR USER2=USERIN);
END DELETE_EMPTY_ACCOUNTS;

/
--------------------------------------------------------
--  DDL for Procedure SETBALANCE_BANK_ACCOUNT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "JOSEPHJUSTN"."SETBALANCE_BANK_ACCOUNT" 
(
  ACCOUNTIN IN INTEGER 
, FINALBALANCE IN FLOAT 
) AS 
BEGIN
    UPDATE BANK_ACCOUNT SET BALANCE=FINALBALANCE WHERE ACCOUNTNUMBER=ACCOUNTIN;
    COMMIT;
END SETBALANCE_BANK_ACCOUNT;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_BANK_USER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "JOSEPHJUSTN"."UPDATE_BANK_USER" 
(
  USERNAMEIN IN VARCHAR2
, FIRSTNAMEIN IN VARCHAR2 
, LASTNAMEIN IN VARCHAR2 
, ADDRESSNUMBERIN IN NUMBER 
, ADDRESSSTREETIN IN VARCHAR2 
, ZIPCODEIN IN NUMBER 
) AS 
BEGIN
  UPDATE BANK_USER 
  SET FIRSTNAME=FIRSTNAMEIN, LASTNAME=LASTNAMEIN, ADDRESSNUMBER=ADDRESSNUMBERIN, ADDRESSSTREET=ADDRESSSTREETIN, ZIPCODE=ZIPCODEIN
  WHERE USERNAME=USERNAMEIN;
END UPDATE_BANK_USER;

/
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "JOSEPHJUSTN"."BANK_ACCOUNT" ADD CONSTRAINT "BANK_ACCOUNT_PK" PRIMARY KEY ("ACCOUNTNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JOSEPHJUSTN"."BANK_ACCOUNT" MODIFY ("ACCOUNTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "JOSEPHJUSTN"."BANK_ACCOUNT" MODIFY ("ACCOUNTTYPE" NOT NULL ENABLE);
  ALTER TABLE "JOSEPHJUSTN"."BANK_ACCOUNT" MODIFY ("APPROVED" NOT NULL ENABLE);
  ALTER TABLE "JOSEPHJUSTN"."BANK_ACCOUNT" MODIFY ("BALANCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK_USER
--------------------------------------------------------

  ALTER TABLE "JOSEPHJUSTN"."BANK_USER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "JOSEPHJUSTN"."BANK_USER" ADD CONSTRAINT "BANK_CUSTOMER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JOSEPHJUSTN"."BANK_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "JOSEPHJUSTN"."BANK_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "JOSEPHJUSTN"."BANK_ACCOUNT" ADD CONSTRAINT "BANK_ACCOUNT_FK1" FOREIGN KEY ("USER1")
	  REFERENCES "JOSEPHJUSTN"."BANK_USER" ("USERNAME") ON DELETE SET NULL ENABLE;
  ALTER TABLE "JOSEPHJUSTN"."BANK_ACCOUNT" ADD CONSTRAINT "BANK_ACCOUNT_FK2" FOREIGN KEY ("USER2")
	  REFERENCES "JOSEPHJUSTN"."BANK_USER" ("USERNAME") ON DELETE SET NULL ENABLE;
