CREATE TABLE CUSTOMERS (C_ID INT, C_USERNAME VARCHAR2(20), C_PASSWORD VARCHAR2(20), C_BALANCE NUMBER(8,2));

CREATE TABLE APPLICANTS (A_ID INT, A_USERNAME VARCHAR2(20), A_PASSWORD VARCHAR2(20), A_BALANCE NUMBER(36,2));

CREATE OR REPLACE PROCEDURE RemCus (USERNAME VARCHAR2) 
IS 
BEGIN
DELETE FROM CUSTOMERS
WHERE C_USERNAME = USERNAME;
END;
/

CREATE SEQUENCE CUSSEQ
    START WITH 1
    INCREMENT BY 1;
    
CREATE SEQUENCE APPSEQ
    START WITH 1
    INCREMENT BY 1;
