--------------------------------------------------------
--  File created - Saturday-December-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BANK_USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BANKING_DB"."BANK_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "BANKING_DB"."BANK_ACCOUNT" 
   (	"BA_ID" NUMBER(*,0), 
	"BA_BALANCE" NUMBER(36,2) DEFAULT (0), 
	"U_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANK_TX
--------------------------------------------------------

  CREATE TABLE "BANKING_DB"."BANK_TX" 
   (	"TX_ID" NUMBER(*,0), 
	"BA_ID" NUMBER(*,0), 
	"BTT_ID" NUMBER(*,0), 
	"TX_AMOUNT" NUMBER(38,2), 
	"TX_TIMESTAMP" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANK_TX_TYPE
--------------------------------------------------------

  CREATE TABLE "BANKING_DB"."BANK_TX_TYPE" 
   (	"BTT_ID" NUMBER(*,0), 
	"BTT_TYPE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANK_USER
--------------------------------------------------------

  CREATE TABLE "BANKING_DB"."BANK_USER" 
   (	"U_ID" NUMBER(*,0), 
	"U_FN" VARCHAR2(4000 BYTE), 
	"U_LN" VARCHAR2(4000 BYTE), 
	"U_USERNAME" VARCHAR2(4000 BYTE), 
	"U_PASSWORD" VARCHAR2(4000 BYTE), 
	"FIRST_NAMES" VARCHAR2(255 CHAR), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BANKING_DB.BANK_ACCOUNT
SET DEFINE OFF;
Insert into BANKING_DB.BANK_ACCOUNT (BA_ID,BA_BALANCE,U_ID,USER_ID) values (1,100,1,null);
Insert into BANKING_DB.BANK_ACCOUNT (BA_ID,BA_BALANCE,U_ID,USER_ID) values (2,500,2,2);
REM INSERTING into BANKING_DB.BANK_TX
SET DEFINE OFF;
REM INSERTING into BANKING_DB.BANK_TX_TYPE
SET DEFINE OFF;
REM INSERTING into BANKING_DB.BANK_USER
SET DEFINE OFF;
Insert into BANKING_DB.BANK_USER (U_ID,U_FN,U_LN,U_USERNAME,U_PASSWORD,FIRST_NAMES,LAST_NAME,PASSWORD,USERNAME) values (1,'steve','k','steve','123',null,null,null,null);
Insert into BANKING_DB.BANK_USER (U_ID,U_FN,U_LN,U_USERNAME,U_PASSWORD,FIRST_NAMES,LAST_NAME,PASSWORD,USERNAME) values (2,'test','test','test','123','jupdate','jj','123','john1');
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "BANKING_DB"."BANK_ACCOUNT" ADD PRIMARY KEY ("BA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BANKING_DB"."BANK_ACCOUNT" MODIFY ("U_ID" NOT NULL ENABLE);
  ALTER TABLE "BANKING_DB"."BANK_ACCOUNT" MODIFY ("BA_BALANCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK_TX
--------------------------------------------------------

  ALTER TABLE "BANKING_DB"."BANK_TX" ADD PRIMARY KEY ("TX_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BANKING_DB"."BANK_TX" MODIFY ("BA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK_TX_TYPE
--------------------------------------------------------

  ALTER TABLE "BANKING_DB"."BANK_TX_TYPE" ADD UNIQUE ("BTT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BANKING_DB"."BANK_TX_TYPE" ADD PRIMARY KEY ("BTT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANK_USER
--------------------------------------------------------

  ALTER TABLE "BANKING_DB"."BANK_USER" ADD UNIQUE ("U_USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BANKING_DB"."BANK_USER" ADD PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BANKING_DB"."BANK_USER" MODIFY ("U_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BANKING_DB"."BANK_USER" MODIFY ("U_USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "BANKING_DB"."BANK_ACCOUNT" ADD CONSTRAINT "FK1979BF0AE5040DEA" FOREIGN KEY ("USER_ID")
	  REFERENCES "BANKING_DB"."BANK_USER" ("U_ID") ENABLE;
  ALTER TABLE "BANKING_DB"."BANK_ACCOUNT" ADD FOREIGN KEY ("U_ID")
	  REFERENCES "BANKING_DB"."BANK_USER" ("U_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANK_TX
--------------------------------------------------------

  ALTER TABLE "BANKING_DB"."BANK_TX" ADD FOREIGN KEY ("BA_ID")
	  REFERENCES "BANKING_DB"."BANK_ACCOUNT" ("BA_ID") ENABLE;
  ALTER TABLE "BANKING_DB"."BANK_TX" ADD FOREIGN KEY ("BTT_ID")
	  REFERENCES "BANKING_DB"."BANK_TX_TYPE" ("BTT_ID") ENABLE;
