package com.revature;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-04-03T04:27:36.079-04:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://revature.com/", name = "MessageGen")
@XmlSeeAlso({ObjectFactory.class})
public interface MessageGen {

    @WebMethod
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://revature.com/", className = "com.revature.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://revature.com/", className = "com.revature.GetMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getMessage();
}
