--Create Users Table
Create Table userAccounts (
    userId number GENERATED BY DEFAULT AS IDENTITY,
    userPassword VARCHAR2(255) NOT NULL,
    username VARCHAR2(255) not null,
    firstname VARCHAR2(255),
    lastname VARCHAR2(255),
    usertype VARCHAR2(255) not null,
    CONSTRAINT userAccounts_pk PRIMARY KEY (userId)
);
--Create Accounts Table
CREATE TABLE bankAccounts (
    accountId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    accountType VARCHAR2(10),
    balance number not null,
    approval VARCHAR2(1),
    primaryOwnerId number,
    CONSTRAINT bankAccounts_pk PRIMARY KEY (accountId)
);
--Create User-Accounts Table
CREATE TABLE UserAccountsLookUp (
    userId number,
    accountId number,
    CONSTRAINT FK_userId FOREIGN KEY (userId)
    REFERENCES userAccounts(userId)
    ON DELETE CASCADE,
    CONSTRAINT FK_accountId FOREIGN KEY (accountId)
    REFERENCES bankAccounts(accountId)
    ON DELETE CASCADE
);

/

CREATE OR REPLACE PROCEDURE delete_user
(v_userId IN NUMBER)
IS
BEGIN
    DELETE FROM USERACCOUNTS
    WHERE USERID = 'v_userId';
END;

/

create or replace PROCEDURE delete_account
(v_accountId IN NUMBER)
IS
BEGIN
    DELETE FROM BANKACCOUNTS
    WHERE ACCOUNTID = v_accountId;
END;