package com.revature.database;

/**
 * CREATE DATABASE TABLES FOR BANKING APP
 */
public interface CreateBank {

	String TRANSACTION_TABLE_NAME = "TRANSACTION";
	String BANK_ACCOUNT_TABLE_NAME = "BANK_ACCOUNT";
	String USER_BANK_ACCOUNT_TABLE_NAME = "USER_BANK_ACCOUNT";
	String USER_TABLE_NAME = "BANK_USER";

	// needs bank account and bank user table to exist
	String CREATE_TRANSACTION_TABLE = "CREATE TABLE " + TRANSACTION_TABLE_NAME + "("
			+ "TRANSACTION_ID NUMBER(16) NOT NULL," + "USER_ID NUMBER(16) NOT NULL," + "ACCOUNT_ID NUMBER(16) NOT NULL,"
			+ "DATE_CREATED DATE DEFAULT (sysdate)," + "AMOUNT NUMBER(19, 4) NOT NULL,"
			+ "PRIMARY KEY (TRANSACTION_ID)," + "FOREIGN KEY(USER_ID) REFERENCES " + USER_TABLE_NAME + "(USER_ID),"
			+ "FOREIGN KEY(ACCOUNT_ID) REFERENCES " + BANK_ACCOUNT_TABLE_NAME + "(ACCOUNT_ID)" + ")";

	String CREATE_BANK_ACCOUNT_TABLE = "CREATE TABLE " + BANK_ACCOUNT_TABLE_NAME + "("
			+ "ACCOUNT_ID NUMBER(16) NOT NULL," + "BALANCE NUMBER(19, 4) NOT NULL,"
			+ "DATE_CREATED DATE DEFAULT (sysdate)," + "PRIMARY KEY (ACCOUNT_ID) " + ")";

	String CREATE_USER_BANK_ACCOUNT_TABLE = "CREATE TABLE " + USER_BANK_ACCOUNT_TABLE_NAME + "("
			+ "USER_ID NUMBER(16) NOT NULL," + "ACCOUNT_ID NUMBER(16) NOT NULL,"
			+ "DATE_CREATED DATE DEFAULT (sysdate)," + "PRIMARY KEY (USER_ID, ACCOUNT_ID),"
			+ "FOREIGN KEY(USER_ID) REFERENCES " + USER_TABLE_NAME + "(USER_ID),"
			+ "FOREIGN KEY(ACCOUNT_ID) REFERENCES " + BANK_ACCOUNT_TABLE_NAME + "(ACCOUNT_ID)" + ")";

	String CREATE_USER_TABLE = "CREATE TABLE " + USER_TABLE_NAME + "(" + "USER_ID NUMBER(16) NOT NULL,"
			+ "USERNAME VARCHAR(20) NOT NULL UNIQUE," + "PASSWORD VARCHAR(20) NOT NULL," + "FNAME VARCHAR(36) NOT NULL,"
			+ "LNAME VARCHAR(36) NOT NULL," + "BIRTHDATE DATE DEFAULT (sysdate)," + "SUPER NUMBER(1),"
			+ "DATE_CREATED DATE DEFAULT (sysdate)," + "PRIMARY KEY (USER_ID) " + ")";

}
