/*
 * Bank App Debug SQL file to test 
 */
SELECT * FROM ACCOUNTS;
----DROP ALL TABLES FROM SQL ASSIGNMENT
/*
--DROP TABLE ALBUM;
--DROP TABLE ARTIST;
--DROP TABLE CUSTOMER;
--DROP TABLE EMPLOYEE;
--DROP TABLE GENRE;
--DROP TABLE INVOICE;
--DROP TABLE INVOICELINE;
--DROP TABLE MEDIATYPE;
--DROP TABLE PLAYLIST;
--DROP TABLE PLAYLISTTRACK;
--DROP TABLE TRACK;
*/


DROP TABLE USERS;
DROP Table ACCOUNTS;
----INSERT DUMMY DATA FOR USERS
INSERT INTO USERS
VALUES (1,1,'Admin','Admin','admin','password',
        '000 Default Ln.','City', 'Zip','ST','USA','(000)000-0000');

INSERT INTO USERS
VALUES (2,0,'Kevin','Hsieh','khsieh','012345',
        '241 hello st','tampa', '93355','FL','USA','(951)824-0227');

INSERT INTO USERS
VALUES (3,0,'K2','SO','rogue','one',
        '123 Galaxy Way','Jedha', 'H-10','MR','NaJedha','(111)111-1111');

----INSERT DUMMY DATA FOR ACCOUNTS
INSERT INTO ACCOUNTS
VALUES (1,2,'1584-4587-4685-5879',0.0,0,NULL,1);

INSERT INTO ACCOUNTS
VALUES (2,2,'4482-1117-5555-9999',0.0,0,NULL,1);

--format: 241 green oaks drive, riverside, ca, 92507            
SELECT * FROM USERS WHERE username='khsieh' AND password='012345';

--test sequence
select USER_ID.NEXTVAL FROM DUAL;
select ACCOUNT_ID.NEXTVAL FROM DUAL;
select USER_ID.CURRVAL FROM DUAL;
select ACCOUNT_ID.CURRVAL FROM DUAL;


