--DEBUG FOR ERS

--drop tables
DROP TABLE ERS_REIMBURSEMENT_TYPE;
DROP TABLE ERS_REIMBURSEMENT_STATUS;
DROP TABLE ERS_REIMBURSEMENTS;
DROP TABLE ERS_USERS;
DROP TABLE ERS_USER_ROLES;

--insert dummy data
INSERT INTO ERS_REIMBURSEMENT_TYPE (RT_TYPE) VALUES ('travel');
INSERT INTO ERS_REIMBURSEMENT_STATUS (RS_STATUS) VALUES ('pending');
INSERT INTO ERS_REIMBURSEMENT_STATUS (RS_STATUS) VALUES ('approved');
INSERT INTO ERS_REIMBURSEMENT_STATUS (RS_STATUS) VALUES ('denied');
INSERT INTO ers_user_roles (UR_ROLES) VALUES ('employee');


--select tests
SELECT rs_status FROM ERS_REIMBURSEMENT_status WHERE Rs_ID=1;
SELECT ur_roles FROM ers_user_roles WHERE ur_id=2;

SELECT * FROM ers_users WHERE u_username='khsieh';
