--Inner
SELECT ALBUM.TITLE
FROM ARTIST INNER JOIN ALBUM
ON ARTIST.ARTISTID= ALBUM.ARTISTID
WHERE ARTIST.ARTISTID=50;

--OUTER RIGHT
SELECT *
FROM ARTIST RIGHT JOIN ALBUM
ON ARTIST.ARTISTID= ALBUM.ARTISTID
WHERE ARTIST.ARTISTID=50;

SELECT *
FROM ARTIST LEFT JOIN ALBUM
ON ARTIST.ARTISTID= ALBUM.ARTISTID
WHERE ARTIST.ARTISTID=50;

--FULL 
SELECT *
FROM ALBUM FULL OUTER JOIN ARTIST 
ON ARTIST.ARTISTID= ALBUM.ARTISTID
WHERE ARTIST.ARTISTID=50;

--SEQUENCE
CREATE SEQUENCE STUDENTS_1
;

SELECT A.EMPLOYEEID AS EMP, B.EMPLOYEEID AS SUP
FROM EMPLOYEE A JOIN EMPLOYEE B
ON A.REPORTSTO =B.EMPLOYEEID;


CREATE VIEW TEST
AS SELECT NAME FROM ARTIST;

SELECT STUDENTS_1.NEXTVAL FROM DUAL;

CREATE SEQUENCE STUDENTS_2
MAXVALUE 50
START WITH 20
INCREMENT BY 3;

SELECT STUDENTS_2.NEXTVAL FROM DUAL;

CREATE VIEW MY_VIEW
AS SELECT ARTIST.NAME,ALBUM.TITLE 
FROM ALBUM INNER JOIN ARTIST
ON ALBUM.ARTISTID=ARTIST.ARTISTID;

SELECT NAME FROM MY_VIEW WHERE NAME LIKE 'I%';
CREATE SEQUENCE IDUNNO
START WITH -5
INCREMENT BY -5;
SELECT IDUNNO.NEXTVAL FROM DUAL;