SELECT * FROM ALBUM WHERE ALBUMID=2 OR ALBUMID = 235;

SELECT NAME FROM ARTIST WHERE ARTISTID=2;

SELECT  LASTNAME FROM EMPLOYEE WHERE TITLE= 'IT Staff' GROUP BY LASTNAME;
SELECT COUNT(EMPLOYEEID),COUNTRY,CITY FROM EMPLOYEE 
GROUP BY COUNTRY,CITY;
--SELECT AGGREGATE FROM GROUP BY HAVING
SELECT COUNT(EMPLOYEEID),COUNTRY,CITY FROM EMPLOYEE 
GROUP BY COUNTRY,CITY HAVING COUNT(EMPLOYEEID)>1;
--ORDER BY
SELECT COUNT(EMPLOYEEID),COUNTRY,CITY FROM EMPLOYEE 
GROUP BY COUNTRY,CITY HAVING COUNT(EMPLOYEEID)>1 
ORDER BY COUNT(EMPLOYEEID);


SELECT CONCAT(NAME,COMPOSER) FROM TRACK FETCH FIRST 5 ROWS ONLY;

/*---SUBQUERIES
SELECT WITHIN A SELECT
NARROW DOWN A RESULTSET
NESTED IN WHERE CLAUSE
2 TYPES- CORRELATED AND NONCORRELATED
NON-CORRELATED- The inner query can execute
independently of the outer query.
--INNER QUERY EXECUTES FIRST, THEN OUTER

CORRELATED- The inner query is not independent.